import fs from 'fs';

let content = fs.readFileSync('src/data/translations.ts', 'utf8');

const arabic = {
  app_title: "خريطة الطريق",
  change_language: "تغيير اللغات",
  lives: "قلوب",
  stars: "نجوم",
  level: "مستوى",
  unlocked: "مفتوح",
  locked: "مقفول",
  unlock_with: "افتح بـ 10 ⭐",
  completed: "مكتمل",
  alphabet_modal_title: "دعنا نتعلم {target}!",
  alphabet_modal_subtitle: "تعلم أبجدية {target}",
  alphabet_modal_write_word: "اكتب هذه الكلمة بـ {target}:",
  alphabet_modal_input_placeholder: "كوّن كلمتك...",
  alphabet_modal_clear: "مسح",
  alphabet_modal_speak: "قراءة بصوت عال",
  alphabet_modal_characters: "أحرف {tab}",
  alphabet_modal_tab_alphabet: "الأبجدية",
  alphabet_modal_tab_word: "تكوين كلمة",
  store_title: "متجر القلوب",
  store_price: "السعر: 3 ⭐ = 1 ❤️",
  store_buy: "شراء قلب",
  store_close: "إغلاق",
  lang_setup_native: "ما هي لغتك الأم؟",
  lang_setup_target: "ما اللغة التي تريد تعلمها؟",
  lang_setup_search: "بحث عن لغة...",
  lang_setup_custom_placeholder: "أو اكتب لغتك الخاصة...",
  lang_setup_custom_button: "اختيار",
  msg_not_enough_stars: "نجوم غير كافية! تحتاج إلى 10 ⭐.",
  msg_out_of_hearts: "نفدت القلوب! اذهب إلى المتجر.",
  msg_level_locked: "هذا المستوى لا يزال مغلقًا!",
  msg_correct: "تهانينا! لقد اجتزت الدرس. 🎁 مكافأة: +5 ⭐ نجوم!",
  profile_user: 'مستخدم',
  profile_joined: 'انضم في 2025',
  lesson_continue: "استمرار",
  lesson_check: "تحقق",
  lesson_skip: "تخطي",
  summary_completed: "اكتمل الدرس!",
  summary_continue: "العودة إلى الخريطة",
  map_start_btn: "لنبدأ!",
  stat_courses: "دورات",
  stat_level: "مستوى",
  stat_success: "نجاح",
  input_title: "ما الكلمات التي يجب أن نتعلمها اليوم؟",
  input_subtitle: "اكتب الكلمات التي تريد تعلمها باللغة {native}. (الحد الأدنى 3 ، الحد الأقصى 5 كلمات)",
  input_word_placeholder: "الكلمة {index}",
  input_start_lesson: "ابدأ الدرس",
  input_error_fill: "الرجاء إدخال 3 كلمات على الأقل.",
  pre_test_title: "اختبر نفسك",
  pre_test_subtitle: "سوف تجري اختبارًا عشوائيًا من الكلمات التي تعلمتها مسبقًا. هل أنت مستعد؟",
  pre_start_test: "ابدأ الاختبار",
  msg_preparing: "جار التحضير...",
  msg_error_preparing: "حدث خطأ أثناء التحضير.",
  lesson_write_meaning: "اكتب المعنى {native} لهذه الكلمة {target}.",
  lesson_write_placeholder: "اكتب المعنى {native} هنا...",
  pre_test_instruction: "انقر فوق الزر أدناه لبدء الاختبار.",
  lesson_choose_translation: "اختر الترجمة الصحيحة",
  lesson_tap_what_you_hear: "انقر على ما تسمعه",
  lesson_type_what_you_hear: "اكتب ما تسمعه",
  lesson_translate_sentence: "ترجم الجملة أدناه",
  lesson_tap_matching_pairs: "اضغط على الأزواج المتطابقة",
  lesson_new_word: "كلمة جديدة",
  lesson_correct_answer: "الإجابة الصحيحة:",
  lesson_great: "رائع!",
  lesson_watch_out: "انتبه لهذا.",
  lesson_remaining_hearts: "القلوب المتبقية: {hearts}",
  summary_subtitle: "عمل رائع، لقد تعلمت كلمات جديدة!",
  summary_test_subtitle: "لقد اجتزت بنجاح هدف اختبر نفسك بنسبة 100%، تهانينا!"
};

const extra = `
Object.assign(translations['Arapça'] = translations['Arapça'] || {}, ${JSON.stringify(arabic, null, 2)});
`;

fs.writeFileSync('src/data/translations.ts', content + "\n" + extra);
